import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { stringify } from 'yaml';
import type { Sources, SurfaceEntry, Term, TestIdEntry } from '../../schema/agent-kb.js';
import { redact, type Redaction } from '../redact.js';
import { PRODUCT_DIR } from '../store.js';
import { ADAPTERS, type Adapter, type AdapterContext } from './adapters.js';
import { scanSource } from './scan.js';

/**
 * Running the adapters and writing `.agent-kb/product`. Two rules enforced here
 * rather than trusted to callers: nothing is ever written to the product
 * repository, and no product source is stored — names, shapes and `file:line`
 * references go into the knowledge base, code does not.
 */

export interface ExtractOptions {
  readonly projectRoot: string;
  readonly sourceRoot: string;
  readonly only?: readonly string[];
  readonly now?: Date;
}

export interface ExtractResult {
  readonly adapters: readonly string[];
  readonly testIds: readonly TestIdEntry[];
  readonly surface: readonly SurfaceEntry[];
  readonly terms: readonly Term[];
  readonly gaps: readonly string[];
  readonly filesRead: number;
  readonly written: readonly string[];
  readonly redactions: readonly Redaction[];
  readonly commit: string | undefined;
}

/** The product's commit, so a claim can be traced to a version of the code. */
function commitOf(sourceRoot: string): string | undefined {
  const result = spawnSync('git', ['rev-parse', 'HEAD'], {
    cwd: sourceRoot,
    encoding: 'utf8',
  });
  const sha = result.status === 0 ? result.stdout.trim() : '';
  return /^[0-9a-f]{40}$/.test(sha) ? sha : undefined;
}

const HEADER = `# Generated by \`understudy extract\` from the product source.
#
# Structure, names and file:line references only — never product code. Every
# entry can be checked against the commit recorded in sources.json.
`;

function writeYaml(
  dir: string,
  name: string,
  data: unknown,
): { path: string; redactions: readonly Redaction[] } {
  const { text, redactions } = redact(stringify(data, { lineWidth: 0 }));
  const path = join(dir, name);
  writeFileSync(path, `${HEADER}${text}`, 'utf8');
  return { path, redactions };
}

export function extract(options: ExtractOptions): ExtractResult {
  const sourceRoot = resolve(options.sourceRoot);
  const productDir = join(options.projectRoot, PRODUCT_DIR);
  const gaps: string[] = [];

  if (!existsSync(sourceRoot)) {
    // A documented level of access, not an error: say what cannot be established.
    return {
      adapters: [],
      testIds: [],
      surface: [],
      terms: [],
      gaps: [
        `No product source at ${sourceRoot}. Nothing could be established from code.`,
        'This is the black-box case: use `understudy survey <url>` and any OpenAPI document instead.',
      ],
      filesRead: 0,
      written: [],
      redactions: [],
      commit: undefined,
    };
  }

  const scan = scanSource(sourceRoot);
  gaps.push(...scan.notes);

  const context: AdapterContext = { files: scan.files };
  const chosen: Adapter[] = ADAPTERS.filter((adapter) =>
    options.only === undefined ? adapter.detect(context) : options.only.includes(adapter.id),
  );

  if (chosen.length === 0) {
    gaps.push('No adapter recognised this stack, so only what any codebase exposes was read.');
  }

  const testIds = new Map<string, TestIdEntry>();
  const surface: SurfaceEntry[] = [];
  const terms: Term[] = [];

  for (const adapter of chosen) {
    const result = adapter.extract(context);
    for (const entry of result.testIds ?? [])
      if (!testIds.has(entry.testId)) testIds.set(entry.testId, entry);
    surface.push(...(result.surface ?? []));
    terms.push(...(result.terms ?? []));
    gaps.push(...(result.gaps ?? []));
  }

  if (testIds.size === 0) {
    gaps.push(
      'No data-testid attributes found. Correlation will not be able to confirm any selector against the source — see docs/guides/finding-elements.',
    );
  }

  const commit = commitOf(sourceRoot);
  if (commit === undefined) {
    gaps.push('The product is not a git checkout, so drift cannot be detected by commit.');
  }

  mkdirSync(productDir, { recursive: true });
  const written: string[] = [];
  const redactions: Redaction[] = [];

  const files = [
    writeYaml(productDir, 'testids.yaml', {
      schemaVersion: 1,
      ...(commit === undefined ? {} : { commit }),
      testIds: [...testIds.values()],
    }),
    writeYaml(productDir, 'surface.yaml', {
      schemaVersion: 1,
      ...(commit === undefined ? {} : { commit }),
      entries: surface,
    }),
    writeYaml(productDir, 'vocabulary.yaml', {
      schemaVersion: 1,
      ...(commit === undefined ? {} : { commit }),
      terms,
    }),
  ];
  for (const file of files) {
    written.push(file.path);
    redactions.push(...file.redactions);
  }

  const sources: Sources = {
    schemaVersion: 1,
    source: sourceRoot,
    ...(commit === undefined ? {} : { commit }),
    extractedAt: (options.now ?? new Date()).toISOString(),
    adapters: chosen.map((a) => a.id),
    // Hashes only — enough to detect that a file changed, never its contents.
    files: scan.files.map((file) => ({ path: file.path, hash: file.hash })),
    gaps,
  };
  const sourcesPath = join(productDir, 'sources.json');
  writeFileSync(sourcesPath, `${JSON.stringify(sources, null, 2)}\n`, 'utf8');
  written.push(sourcesPath);

  return {
    adapters: chosen.map((a) => a.id),
    testIds: [...testIds.values()],
    surface,
    terms,
    gaps,
    filesRead: scan.files.length,
    written,
    redactions,
    commit,
  };
}

export function formatExtractResult(result: ExtractResult): string {
  const lines = [''];

  if (result.written.length === 0) {
    lines.push('Nothing was extracted.');
    for (const gap of result.gaps) lines.push(`  ${gap}`);
    return lines.join('\n');
  }

  lines.push(
    `Read ${String(result.filesRead)} file(s) using: ${result.adapters.join(', ') || 'none'}`,
  );
  lines.push(`  ${String(result.testIds.length)} test id(s)`);
  lines.push(
    `  ${String(result.surface.filter((e) => e.kind === 'route').length)} route(s), ` +
      `${String(result.surface.filter((e) => e.kind === 'endpoint').length)} endpoint(s)`,
  );
  lines.push(`  ${String(result.terms.length)} user-visible label(s)`);
  lines.push(`  commit ${result.commit ?? 'unknown'}`);

  if (result.redactions.length > 0) {
    lines.push('', `  Redacted before writing: ${String(result.redactions.length)} item(s).`);
  }

  if (result.gaps.length > 0) {
    lines.push('', '  Could not be established:');
    for (const gap of result.gaps.slice(0, 8)) lines.push(`    - ${gap}`);
  }

  lines.push('', '  Now re-survey a route to confirm its selectors against the source:');
  lines.push('    understudy survey <url>');

  return lines.join('\n');
}
