import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { isAbsolute, join, relative, resolve, sep } from 'node:path';
import { stringify } from 'yaml';
import type {
  Sources,
  SurfaceEntry,
  Term,
  TestActionEntry,
  TestIdEntry,
  TestLocatorEntry,
} from '../../schema/agent-kb.js';
import { adoptOwner } from '../owner.js';
import { redact, type Redaction } from '../redact.js';
import { PRODUCT_DIR } from '../store.js';
import { ADAPTERS, type Adapter, type AdapterContext } from './adapters.js';
import { scanSource, type SourceFileRef } from './scan.js';
import { hashContent } from '../working-tree.js';

/**
 * Running the adapters and writing `.agent-kb/product`. Two rules enforced here
 * rather than trusted to callers: nothing is ever written to the product
 * repository, and no product source is stored — names, shapes and `file:line`
 * references go into the knowledge base, code does not.
 */

export interface ExtractOptions {
  readonly projectRoot: string;
  readonly sourceRoot: string;
  readonly only?: readonly string[];
  readonly now?: Date;
  /** Directories of the product to leave out of the scan, so a template app is not taken for it. */
  readonly exclude?: readonly string[];
  /** An OpenAPI document to read, relative to `projectRoot` — e.g. what `artisan l5-swagger:generate` wrote. */
  readonly openapi?: string;
  /** Work out and report everything, write nothing. */
  readonly dryRun?: boolean;
}

export interface ExtractResult {
  readonly adapters: readonly string[];
  readonly testIds: readonly TestIdEntry[];
  readonly surface: readonly SurfaceEntry[];
  readonly terms: readonly Term[];
  /** Role locators and page object actions read from existing tests; evidence, not truth. */
  readonly fromTests: { readonly locators: number; readonly actions: number };
  readonly gaps: readonly string[];
  readonly filesRead: number;
  readonly written: readonly string[];
  /** With `dryRun`: the files that a real run would write. */
  readonly wouldWrite: readonly string[];
  readonly dryRun: boolean;
  readonly redactions: readonly Redaction[];
  readonly commit: string | undefined;
}

/** The product's commit, so a claim can be traced to a version of the code. */
function commitOf(sourceRoot: string): string | undefined {
  const result = spawnSync('git', ['rev-parse', 'HEAD'], {
    cwd: sourceRoot,
    encoding: 'utf8',
  });
  const sha = result.status === 0 ? result.stdout.trim() : '';
  return /^[0-9a-f]{40}$/.test(sha) ? sha : undefined;
}

/** Generated specs are large; this only guards against reading something that is not one. */
const MAX_SPEC_BYTES = 32 * 1024 * 1024;

function readSpec(
  projectRoot: string,
  sourceRoot: string,
  spec: string,
  gaps: string[],
): SourceFileRef | undefined {
  const full = isAbsolute(spec) ? spec : resolve(projectRoot, spec);
  try {
    if (statSync(full).size > MAX_SPEC_BYTES) {
      gaps.push(
        `${spec}: larger than ${String(MAX_SPEC_BYTES)} bytes, so it was not read as an OpenAPI document`,
      );
      return undefined;
    }
    const text = readFileSync(full, 'utf8');
    const inside = relative(sourceRoot, full);
    return {
      // Inside the product it is a product path like any other; outside, the path as given.
      path: inside.startsWith('..') || isAbsolute(inside) ? full : inside.split(sep).join('/'),
      lines: text.split('\n'),
      hash: hashContent(text),
    };
  } catch {
    gaps.push(
      `${spec}: the OpenAPI document could not be read — generate it first, then run extract again`,
    );
    return undefined;
  }
}

const HEADER = `# Generated by \`cue extract\` from the product source.
#
# Structure, names and file:line references only — never product code. Every
# entry can be checked against the commit recorded in sources.json.
`;

function writeYaml(
  root: string,
  dir: string,
  name: string,
  data: unknown,
  dryRun: boolean,
): { path: string; redactions: readonly Redaction[] } {
  const { text, redactions } = redact(stringify(data, { lineWidth: 0 }));
  const path = join(dir, name);
  if (!dryRun) {
    writeFileSync(path, `${HEADER}${text}`, 'utf8');
    adoptOwner(path, root);
  }
  return { path, redactions };
}

export function extract(options: ExtractOptions): ExtractResult {
  const sourceRoot = resolve(options.sourceRoot);
  const productDir = join(options.projectRoot, PRODUCT_DIR);
  const gaps: string[] = [];

  if (!existsSync(sourceRoot)) {
    // A documented level of access, not an error: say what cannot be established.
    return {
      adapters: [],
      testIds: [],
      surface: [],
      terms: [],
      fromTests: { locators: 0, actions: 0 },
      gaps: [
        `No product source at ${sourceRoot}. Nothing could be established from code.`,
        'This is the black-box case: use `cue survey <url>` and any OpenAPI document instead.',
      ],
      filesRead: 0,
      written: [],
      wouldWrite: [],
      dryRun: options.dryRun === true,
      redactions: [],
      commit: undefined,
    };
  }

  const scan = scanSource(sourceRoot, undefined, { exclude: options.exclude ?? [] });
  gaps.push(...scan.notes);

  // The suite in the directory Cue runs in. Skipped when it is the product itself, or sits
  // inside it, where the product scan has already read it.
  const projectRoot = resolve(options.projectRoot);
  const insideProduct = !relative(sourceRoot, projectRoot).startsWith('..');
  const projectScan = insideProduct
    ? undefined
    : scanSource(projectRoot, undefined, {
        // The product may sit inside the suite: leave it to the scan above.
        exclude: relative(projectRoot, sourceRoot).startsWith('..')
          ? []
          : [relative(projectRoot, sourceRoot).split(sep).join('/')],
      });

  const specs: SourceFileRef[] = [];
  if (options.openapi !== undefined) {
    const spec = readSpec(options.projectRoot, sourceRoot, options.openapi, gaps);
    if (spec !== undefined) specs.push(spec);
  }

  const context: AdapterContext = {
    files: scan.files,
    ...(projectScan === undefined ? {} : { projectFiles: projectScan.files }),
    ...(specs.length === 0 ? {} : { specs }),
  };
  const chosen: Adapter[] = ADAPTERS.filter((adapter) =>
    options.only === undefined ? adapter.detect(context) : options.only.includes(adapter.id),
  );

  if (chosen.length === 0) {
    gaps.push('No adapter recognised this stack, so only what any codebase exposes was read.');
  }

  const testIds = new Map<string, TestIdEntry>();
  const surface: SurfaceEntry[] = [];
  const terms: Term[] = [];
  const testLocators = new Map<string, TestLocatorEntry>();
  const testActions = new Map<string, TestActionEntry>();

  for (const adapter of chosen) {
    const result = adapter.extract(context);
    for (const entry of result.testIds ?? [])
      if (!testIds.has(entry.testId)) testIds.set(entry.testId, entry);
    surface.push(...(result.surface ?? []));
    terms.push(...(result.terms ?? []));
    for (const entry of result.fromTests?.locators ?? []) {
      const key = `${entry.route}\u0000${entry.role}\u0000${entry.name ?? ''}`;
      if (!testLocators.has(key)) testLocators.set(key, entry);
    }
    for (const entry of result.fromTests?.actions ?? []) {
      const key = `${entry.route}\u0000${entry.symbol}`;
      if (!testActions.has(key)) testActions.set(key, entry);
    }
    gaps.push(...(result.gaps ?? []));
  }

  if (testIds.size === 0) {
    gaps.push(
      'No data-testid attributes found. Correlation will not be able to confirm any selector against the source — see docs/guides/finding-elements.',
    );
  }

  const commit = commitOf(sourceRoot);
  if (commit === undefined) {
    gaps.push('The product is not a git checkout, so drift cannot be detected by commit.');
  }

  const dryRun = options.dryRun === true;
  if (!dryRun) mkdirSync(productDir, { recursive: true });
  const written: string[] = [];
  const redactions: Redaction[] = [];

  const files = [
    writeYaml(
      options.projectRoot,
      productDir,
      'testids.yaml',
      {
        schemaVersion: 1,
        ...(commit === undefined ? {} : { commit }),
        testIds: [...testIds.values()],
      },
      dryRun,
    ),
    writeYaml(
      options.projectRoot,
      productDir,
      'surface.yaml',
      {
        schemaVersion: 1,
        ...(commit === undefined ? {} : { commit }),
        entries: surface,
      },
      dryRun,
    ),
    writeYaml(
      options.projectRoot,
      productDir,
      'vocabulary.yaml',
      {
        schemaVersion: 1,
        ...(commit === undefined ? {} : { commit }),
        terms,
      },
      dryRun,
    ),
  ];
  // Rewritten every time, so a suite that no longer says anything does not leave old claims behind.
  const fromTestsPath = join(productDir, 'from-tests.yaml');
  if (testLocators.size > 0 || testActions.size > 0) {
    files.push(
      writeYaml(
        options.projectRoot,
        productDir,
        'from-tests.yaml',
        {
          schemaVersion: 1,
          ...(commit === undefined ? {} : { commit }),
          locators: [...testLocators.values()],
          actions: [...testActions.values()],
        },
        dryRun,
      ),
    );
  } else if (!dryRun && existsSync(fromTestsPath)) {
    rmSync(fromTestsPath);
  }

  for (const file of files) {
    written.push(file.path);
    redactions.push(...file.redactions);
  }

  const sources: Sources = {
    schemaVersion: 1,
    source: sourceRoot,
    ...(commit === undefined ? {} : { commit }),
    extractedAt: (options.now ?? new Date()).toISOString(),
    adapters: chosen.map((a) => a.id),
    // Hashes only — enough to detect that a file changed, never its contents.
    files: [...scan.files, ...specs].map((file) => ({ path: file.path, hash: file.hash })),
    gaps,
  };
  const sourcesPath = join(productDir, 'sources.json');
  if (!dryRun) {
    writeFileSync(sourcesPath, `${JSON.stringify(sources, null, 2)}\n`, 'utf8');
    adoptOwner(sourcesPath, options.projectRoot);
  }
  written.push(sourcesPath);

  return {
    adapters: chosen.map((a) => a.id),
    testIds: [...testIds.values()],
    surface,
    terms,
    fromTests: { locators: testLocators.size, actions: testActions.size },
    gaps,
    filesRead: scan.files.length,
    written: dryRun ? [] : written,
    wouldWrite: dryRun ? written : [],
    dryRun,
    redactions,
    commit,
  };
}

export function formatExtractResult(result: ExtractResult): string {
  const lines = [''];

  if (result.written.length === 0 && result.wouldWrite.length === 0) {
    lines.push('Nothing was extracted.');
    for (const gap of result.gaps) lines.push(`  ${gap}`);
    return lines.join('\n');
  }

  lines.push(
    `Read ${String(result.filesRead)} file(s) using: ${result.adapters.join(', ') || 'none'}`,
  );
  lines.push(`  ${String(result.testIds.length)} test id(s)`);
  lines.push(
    `  ${String(result.surface.filter((e) => e.kind === 'route').length)} route(s), ` +
      `${String(result.surface.filter((e) => e.kind === 'endpoint').length)} endpoint(s)`,
  );
  lines.push(`  ${String(result.terms.length)} user-visible label(s)`);
  if (result.fromTests.locators > 0 || result.fromTests.actions > 0) {
    lines.push(
      `  ${String(result.fromTests.locators)} locator(s) and ${String(result.fromTests.actions)} page object action(s) from existing tests (inferred until a survey agrees)`,
    );
  }
  lines.push(`  commit ${result.commit ?? 'unknown'}`);

  if (result.dryRun) {
    lines.push('', '  Dry run — nothing was written. A real run would write:');
    for (const path of result.wouldWrite) lines.push(`    ${path}`);
  }

  if (result.redactions.length > 0) {
    lines.push('', `  Redacted before writing: ${String(result.redactions.length)} item(s).`);
  }

  if (result.gaps.length > 0) {
    lines.push('', '  Could not be established:');
    for (const gap of result.gaps.slice(0, 8)) lines.push(`    - ${gap}`);
  }

  if (!result.dryRun) {
    lines.push('', '  Now re-survey a route to confirm its selectors against the source:');
    lines.push('    cue survey <url>');
  }

  return lines.join('\n');
}
