import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * The ESLint setup is two files. `eslint.cue.mjs` is Cue's, written whole and
 * rewritten by `sync`; `eslint.config.mjs` is the user's, created once if absent
 * and never changed by Cue afterwards. The user's config imports the overlay, and
 * what comes after `...cue` in its array wins — so exceptions for a folder of tests
 * live in the user's file and survive every `sync`.
 */

export const OVERLAY_PATH = 'eslint.cue.mjs';
export const OVERLAY_SPECIFIER = `./${OVERLAY_PATH}`;

export const ESLINT_CONFIGS = [
  'eslint.config.js',
  'eslint.config.mjs',
  'eslint.config.cjs',
  'eslint.config.ts',
  'eslint.config.mts',
] as const;

/** The config the project already has, or the one `init` would create. */
export function eslintConfigPath(projectRoot: string): string {
  return ESLINT_CONFIGS.find((name) => existsSync(join(projectRoot, name))) ?? 'eslint.config.mjs';
}

export const overlayBody = `import cue from '@wiluszdamian/cue-eslint-plugin';

// Generated by Cue and rewritten by \`cue sync\`. Do not edit: put your own rules and
// exceptions in eslint.config.mjs, after \`...cue\`.
export default [
  ...cue.configs.recommended,
];
`;

export const userConfigSeed = `import cue from '${OVERLAY_SPECIFIER}';

// Yours — Cue does not rewrite this file. The constitution's rules come from
// ${OVERLAY_PATH}; entries after \`...cue\` win, so exceptions go here.
export default [
  ...cue,
];
`;

export const hasOverlayImport = (content: string): boolean => content.includes(OVERLAY_PATH);

/** The two lines to paste, for a config that cannot be wired automatically. */
export function wiringLines(binding = 'cue'): string {
  return `import ${binding} from '${OVERLAY_SPECIFIER}';  …and, first in the exported array:  ...${binding},`;
}

const IMPORT_LINE = /^import\s[^;]*?from\s+['"][^'"]+['"];?\s*$/gm;

/**
 * Wires the overlay into an existing config: one import, one spread. Only a plain
 * `export default [` is recognised — anything else (`defineConfig`, a CommonJS
 * `module.exports`) is someone's own code, and `undefined` leaves it alone for
 * `doctor` to point at.
 */
export function wireOverlay(existing: string): string | undefined {
  if (hasOverlayImport(existing)) return undefined;

  const array = /^export default \[[ \t]*$/m.exec(existing);
  if (!array) return undefined;

  const binding = /\bcue\b/.test(existing) ? 'cueOverlay' : 'cue';
  const insertAt = array.index + array[0].length;
  const withSpread = `${existing.slice(0, insertAt)}\n  ...${binding},${existing.slice(insertAt)}`;

  const imports = [...withSpread.matchAll(IMPORT_LINE)];
  const last = imports[imports.length - 1];
  const importLine = `import ${binding} from '${OVERLAY_SPECIFIER}';`;
  if (last === undefined) return `${importLine}\n${withSpread}`;

  const end = last.index + last[0].length;
  return `${withSpread.slice(0, end)}\n${importLine}${withSpread.slice(end)}`;
}

export function configImportsOverlay(projectRoot: string): boolean {
  const config = ESLINT_CONFIGS.find((name) => existsSync(join(projectRoot, name)));
  return config !== undefined && hasOverlayImport(readFileSync(join(projectRoot, config), 'utf8'));
}
