import type { Ownership } from '@wiluszdamian/cue-engine';
import type { DesiredFile } from '../install.js';
import { runCommand } from '../package-manager.js';
import { scaffoldFiles, SCAFFOLD_GITIGNORE } from './scaffold.js';
import type { Target, TargetContext } from './types.js';

/**
 * The baseline: what every project gets, whatever agents are in play. `AGENTS.md`
 * carries the ownership table because a skill cannot announce that it outranks
 * another skill, which is the one thing arbitration has to do.
 */

export const CUE_BEGIN = '<!-- BEGIN CUE -->';
export const CUE_END = '<!-- END CUE -->';

const GITIGNORE_BEGIN = '# BEGIN CUE';
const GITIGNORE_END = '# END CUE';

function ownershipTable(ownership: Ownership): string {
  const rows = ownership.topics.map((topic) => {
    const wins = topic.precedence === 'absolute' ? ' **(wins)**' : '';
    const channel = topic.channel ? ` _via ${topic.channel}_` : '';
    return `| ${topic.topic} | \`${topic.owner}\`${wins}${channel} |`;
  });
  return ['| Topic | Decided by |', '| --- | --- |', ...rows].join('\n');
}

function agentsBody(context: TargetContext): string {
  const { rules, packageManager } = context;
  const enforced = rules.constitution.rules.filter((r) => r.detector.kind !== 'manual');
  const manual = rules.constitution.rules.filter((r) => r.detector.kind === 'manual');

  return `
<!-- Generated by Cue ${context.cueVersion}. Edits inside this block are
     overwritten by \`cue sync\`; write your own guidance outside it. -->

## Testing conventions (Cue)

This project uses [Cue](https://github.com/wiluszdamian/cue). Test
code follows a constitution that is mechanically enforced — ${enforced.length} of the
${rules.constitution.rules.length} rules are ESLint rules, so ignoring them fails the build rather
than the review.

Run \`${runCommand(packageManager, 'lint')}\` before you consider a change finished.

### Who decides what

Several sources of Playwright knowledge are in play — the official Playwright
skills, Playwright MCP, a general best-practices skill — and none of them knows
the others exist. When they disagree, this table decides. An owner marked
**(wins)** outranks every other source, including one that states the opposite
confidently.

${ownershipTable(rules.ownership)}

**A topic that is not in this table is a gap, not an invitation to improvise.**
Say so and ask, rather than inventing a convention on the spot.

### The rules, in short

${enforced.map((r) => `- **${r.id}** — ${r.title.replace(/\s+/g, ' ').trim()}`).join('\n')}

${
  manual.length > 0
    ? `Checked in review rather than by the linter, and binding all the same:

${manual.map((r) => `- **${r.id}** — ${r.title.replace(/\s+/g, ' ').trim()}`).join('\n')}
`
    : ''
}
Each rule's full reasoning, with a correct example, is one command away:

\`\`\`bash
npx @wiluszdamian/cue explain <rule-id>
\`\`\`

### Selectors

Never invent a selector. Every selector must come from \`.agent-kb/\` or from an
exploration you ran in this session. A model asked for a selector it has never
seen will produce a plausible one, and a plausible selector fails at runtime in a
way that reads like an application bug.
`;
}

const GITIGNORE_BODY = `
# Cue keeps .agent-kb/ in version control on purpose: it is knowledge
# about the application that should outlive a session, and it gets reviewed like
# any other code.
.cue/cache/
`;

function gitignoreBody(context: TargetContext): string {
  return context.scaffold === false ? GITIGNORE_BODY : GITIGNORE_BODY + SCAFFOLD_GITIGNORE;
}

export const baselineTarget: Target = {
  id: 'agents',
  name: 'AGENTS.md baseline',
  summary: 'Ownership table and conventions, read natively by every agent but Claude Code',
  baseline: true,

  files(context: TargetContext): DesiredFile[] {
    return [
      {
        path: 'AGENTS.md',
        target: 'agents',
        content: agentsBody(context),
        region: { begin: CUE_BEGIN, end: CUE_END },
        reason: 'the always-loaded layer: ownership table and enforced conventions',
      },
      {
        path: '.gitignore',
        target: 'agents',
        content: gitignoreBody(context),
        region: { begin: GITIGNORE_BEGIN, end: GITIGNORE_END },
        reason: 'ignore the Cue cache, but never .agent-kb',
      },
      {
        path: 'eslint.config.mjs',
        target: 'agents',
        // Only when no config exists: a flat config is code, and pattern-matching
        // into someone's own is how a tool corrupts what it did not understand.
        content: `import cue from '@wiluszdamian/cue-eslint-plugin';

// The constitution as ESLint rules: the half of the guarantee that holds with no
// agent involved.
export default [
  ...cue.configs.recommended,
];
`,
        reason: 'the mechanical guarantee — without this nothing enforces the constitution',
      },
      {
        path: '.agent-kb/README.md',
        target: 'agents',
        content: `# .agent-kb

What this repository knows about the application under test. Nobody else can
supply this layer: no model has ever seen your application.

Two sources feed it:

- \`cue extract\` reads the product's source and
  extracts facts — routes, endpoints, entities, roles, and the \`data-testid\`
  values that actually exist — each with a \`file:line\` reference.
- \`cue survey <url>\` drives the running
  application and records what is really on the page.

## Rules for this directory

- **It is committed.** It is knowledge meant to outlive a session, and it is
  reviewed like any other code.
- **Every entry carries a freshness marker.** An entry that has gone stale is a
  lead to verify, not a fact to use. A knowledge base that confidently reports a
  selector which no longer exists is worse than no knowledge base at all.
- **Structure only, never product source.** \`extract\` reads a repository you may
  not own. Names, shapes and references go in here; code does not.

This skeleton marks where their output will belong.
`,
        reason: 'the knowledge base skeleton, with its lifecycle rules',
      },
      ...(context.scaffold === false ? [] : scaffoldFiles(context)),
    ];
  },
};
