import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { parse, stringify } from 'yaml';
import {
  RouteMapSchema,
  TestIdsSchema,
  type Confidence,
  type KbElement,
  type RouteMap,
  type TestIds,
} from '../schema/agent-kb.js';
import type { Freshness } from '../schema/agent-kb.js';
import { freshnessOf } from './freshness.js';
import { redact, type Redaction } from './redact.js';
import { routeToFilename } from './snapshot/index.js';

/**
 * Reading and writing `.agent-kb`. Two invariants live here rather than in the
 * callers: nothing is written unredacted, since the directory is committed, and
 * nothing is read without its freshness, so a six-month-old selector cannot pass
 * for a fact.
 */

export const APP_MAP_DIR = '.agent-kb/app-map';
export const PRODUCT_DIR = '.agent-kb/product';

export interface KbPaths {
  readonly root: string;
}

export function appMapDir(root: string): string {
  return join(root, APP_MAP_DIR);
}

export function routeMapPath(root: string, route: string): string {
  return join(appMapDir(root), `${routeToFilename(route)}.yaml`);
}

export interface WriteResult {
  readonly path: string;
  readonly redactions: readonly Redaction[];
}

const HEADER = `# Generated by \`understudy survey\`. Reviewed like any other code.
#
# Every entry carries verifiedAt. An entry that has gone stale is a lead to
# verify, not a fact to use — see docs/knowledge-base.md.
`;

export function writeRouteMap(root: string, map: RouteMap): WriteResult {
  const parsed = RouteMapSchema.parse(map);
  const yaml = stringify(parsed, { lineWidth: 0 });

  // On the serialised document, so it catches every field.
  const { text, redactions } = redact(yaml);

  const path = routeMapPath(root, parsed.route);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${HEADER}${text}`, 'utf8');

  return { path, redactions };
}

export interface LoadedRouteMap {
  readonly map: RouteMap;
  readonly freshness: Freshness;
  readonly path: string;
}

export function readRouteMap(root: string, route: string, now?: Date): LoadedRouteMap | undefined {
  const path = routeMapPath(root, route);
  if (!existsSync(path)) return undefined;

  const map = RouteMapSchema.parse(parse(readFileSync(path, 'utf8')));
  return { map, freshness: freshnessOf(map.verifiedAt, now), path };
}

export function readAllRouteMaps(root: string, now?: Date): LoadedRouteMap[] {
  const dir = appMapDir(root);
  if (!existsSync(dir)) return [];

  const maps: LoadedRouteMap[] = [];
  for (const entry of readdirSync(dir)) {
    if (!entry.endsWith('.yaml')) continue;
    const path = join(dir, entry);
    try {
      const map = RouteMapSchema.parse(parse(readFileSync(path, 'utf8')));
      maps.push({ map, freshness: freshnessOf(map.verifiedAt, now), path });
    } catch {
      // Skipped rather than crashing every consumer; `doctor` reports it.
    }
  }
  return maps.sort((a, b) => a.map.route.localeCompare(b.map.route));
}

export function readTestIds(root: string): TestIds | undefined {
  const path = join(root, PRODUCT_DIR, 'testids.yaml');
  if (!existsSync(path)) return undefined;
  try {
    return TestIdsSchema.parse(parse(readFileSync(path, 'utf8')));
  } catch {
    return undefined;
  }
}

/** Neither source alone proves a `data-testid` is real *and* reachable. */
export function correlate(
  elements: readonly KbElement[],
  testIds: TestIds | undefined,
): KbElement[] {
  if (!testIds || testIds.testIds.length === 0) return [...elements];

  return elements.map((element) => {
    const candidate = element.name === undefined ? undefined : match(element.name, testIds);
    if (candidate === undefined) return element;

    // Seen running and present in the source: the only combination that earns this.
    return { ...element, testId: candidate, confidence: 'confirmed' satisfies Confidence };
  });
}

/**
 * The test id for an accessible name, or nothing.
 *
 * Test ids are qualified by area, so demanding the whole id equal the name left
 * `confirmed` unreachable — on a real survey it matched 1 of 15. A name now
 * matches any run of whole segments, never a substring: `Log in` meets
 * `login-submit` but not `blogin-x`. Ambiguous matches confirm nothing, since
 * `Password` against both `login-password` and `reset-password` identifies neither.
 */
function match(name: string, testIds: TestIds): string | undefined {
  const wanted = normalise(name);
  if (wanted.length === 0) return undefined;

  const exact = testIds.testIds.find((entry) => normalise(entry.testId) === wanted);
  if (exact) return exact.testId;

  const candidates = testIds.testIds.filter((entry) => segmentRuns(entry.testId).has(wanted));
  return candidates.length === 1 ? candidates[0]?.testId : undefined;
}

/** Every run of consecutive segments in an id, joined: `a-b-c` → a, ab, abc, b, bc, c. */
function segmentRuns(testId: string): Set<string> {
  const segments = testId
    // camelCase and kebab/snake are both in the wild, often in one codebase.
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^a-zA-Z0-9]+/)
    .map((segment) => segment.toLowerCase())
    .filter((segment) => segment.length > 0);

  const runs = new Set<string>();
  for (let start = 0; start < segments.length; start += 1) {
    let joined = '';
    for (const segment of segments.slice(start)) {
      joined += segment;
      runs.add(joined);
    }
  }
  return runs;
}

function normalise(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '');
}

/** Test ids the source has but no survey ever saw — dead, or behind a flag. */
export function codeOnlyTestIds(
  maps: readonly LoadedRouteMap[],
  testIds: TestIds | undefined,
): string[] {
  if (!testIds) return [];
  const seen = new Set(
    maps.flatMap((m) => m.map.elements.flatMap((e) => (e.testId === undefined ? [] : [e.testId]))),
  );
  return testIds.testIds.map((t) => t.testId).filter((id) => !seen.has(id));
}
