import { adoptOwner } from './owner.js';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { parse, stringify } from 'yaml';
import { ZodError } from 'zod';
import {
  RouteMapFileV2Schema,
  RouteMapSchema,
  TestIdsSchema,
  type RouteMap,
  type TestIds,
} from '../schema/agent-kb.js';
import type { Freshness } from '../schema/agent-kb.js';
import { freshnessOf } from './freshness.js';
import { APP_MAP_DIR, PRODUCT_DIR } from './paths.js';
import { redact, type Redaction } from './redact.js';
import { parseRouteMapFile, readSourceIndex, serializeRouteMap } from './route-map-file.js';
import { routeToFilename } from './snapshot/index.js';

/**
 * Reading and writing `.agent-kb`. Two invariants live here rather than in the
 * callers: nothing is written unredacted, since the directory is committed, and
 * nothing is read without its freshness, so a six-month-old selector cannot pass
 * for a fact.
 */

export { APP_MAP_DIR, PRODUCT_DIR };
export { correlate } from './correlate.js';

export interface KbPaths {
  readonly root: string;
}

export function appMapDir(root: string): string {
  return join(root, APP_MAP_DIR);
}

export function routeMapPath(root: string, route: string): string {
  return join(appMapDir(root), `${routeToFilename(route)}.yaml`);
}

/** Where a map lives, as shown to people and cited in evidence: always forward slashes. */
function displayPathOf(route: string): string {
  return `${APP_MAP_DIR}/${routeToFilename(route)}.yaml`;
}

export interface WriteResult {
  readonly path: string;
  readonly redactions: readonly Redaction[];
}

const HEADER = `# Generated by \`cue survey\`. Reviewed like any other code.
#
# Every element says what it rests on (evidence), where it stands (status) and
# when it was last confirmed. An entry that has gone stale is a lead to
# verify, not a fact to use — see docs/guides/keeping-it-current.md.
`;

/** Always written as the current schema version, whatever version the map was read as. */
export function writeRouteMap(root: string, map: RouteMap): WriteResult {
  const parsed = RouteMapSchema.parse(map);
  const file = RouteMapFileV2Schema.parse(
    serializeRouteMap(parsed, {
      displayPath: displayPathOf(parsed.route),
      sources: readSourceIndex(root),
    }),
  );
  const yaml = stringify(file, { lineWidth: 0 });

  // On the serialised document, so it catches every field.
  const { text, redactions } = redact(yaml);

  const path = routeMapPath(root, parsed.route);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${HEADER}${text}`, 'utf8');
  adoptOwner(path, root);

  return { path, redactions };
}

export interface LoadedRouteMap {
  readonly map: RouteMap;
  readonly freshness: Freshness;
  readonly path: string;
  /** The version the file is stored as, which is not what it was read as: both read the same. */
  readonly fileVersion: 1 | 2;
}

export function readRouteMap(root: string, route: string, now?: Date): LoadedRouteMap | undefined {
  const path = routeMapPath(root, route);
  if (!existsSync(path)) return undefined;

  const { map, fileVersion } = parseRouteMapFile(parse(readFileSync(path, 'utf8')), {
    displayPath: displayPathOf(route),
    sources: readSourceIndex(root),
  });
  return { map, freshness: freshnessOf(map.verifiedAt, now), path, fileVersion };
}

export interface InvalidRouteMap {
  readonly path: string;
  /** One line, so a report can print it as it stands. */
  readonly reason: string;
}

export interface RouteMapReading {
  readonly maps: readonly LoadedRouteMap[];
  /** Files that exist but could not be used. Silence about them would read as a clean map. */
  readonly invalid: readonly InvalidRouteMap[];
}

function reasonOf(error: unknown): string {
  if (error instanceof ZodError) {
    const issue = error.issues[0];
    return issue === undefined
      ? 'does not match the route map schema'
      : `${issue.path.join('.') || 'file'}: ${issue.message}`;
  }
  const message = error instanceof Error ? error.message : String(error);
  return message.split('\n')[0] ?? message;
}

export function readAllRouteMapsWithErrors(root: string, now?: Date): RouteMapReading {
  const dir = appMapDir(root);
  if (!existsSync(dir)) return { maps: [], invalid: [] };

  const sources = readSourceIndex(root);
  const maps: LoadedRouteMap[] = [];
  const invalid: InvalidRouteMap[] = [];
  for (const entry of readdirSync(dir).sort()) {
    if (!entry.endsWith('.yaml')) continue;
    const path = join(dir, entry);
    try {
      const { map, fileVersion } = parseRouteMapFile(parse(readFileSync(path, 'utf8')), {
        displayPath: `${APP_MAP_DIR}/${entry}`,
        sources,
      });
      maps.push({ map, freshness: freshnessOf(map.verifiedAt, now), path, fileVersion });
    } catch (error) {
      invalid.push({ path, reason: reasonOf(error) });
    }
  }
  return { maps: maps.sort((a, b) => a.map.route.localeCompare(b.map.route)), invalid };
}

/** The usable maps only. A consumer that must not hide broken files uses the variant above. */
export function readAllRouteMaps(root: string, now?: Date): LoadedRouteMap[] {
  return [...readAllRouteMapsWithErrors(root, now).maps];
}

export function readTestIds(root: string): TestIds | undefined {
  const path = join(root, PRODUCT_DIR, 'testids.yaml');
  if (!existsSync(path)) return undefined;
  try {
    return TestIdsSchema.parse(parse(readFileSync(path, 'utf8')));
  } catch {
    return undefined;
  }
}

/** Test ids the source has but no survey ever saw — dead, or behind a flag. */
export function codeOnlyTestIds(
  maps: readonly LoadedRouteMap[],
  testIds: TestIds | undefined,
): string[] {
  if (!testIds) return [];
  const seen = new Set(
    maps.flatMap((m) => m.map.elements.flatMap((e) => (e.testId === undefined ? [] : [e.testId]))),
  );
  return testIds.testIds.map((t) => t.testId).filter((id) => !seen.has(id));
}
